name: e_commerce_ui
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  sizer: ^2.0.15
  dotted_line: ^3.2.2
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Bad Script
      fonts:
        - asset: assets/fonts/BadScript-Regular.ttf

    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/JosefinSans-Italic.ttf
          style: italic
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/JosefinSans-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-MediumItalic.ttf
          weight: 500
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_ic.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_ic.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_splash.png

  android_12:
    color: "#ffffff"
    image: assets/images/logo_splash.png
    icon_background_color: "#ffffff"
